export const countries = [
  { code: "US", iso3: "USA", name: "United States", flag: "🇺🇸" },
  { code: "KR", iso3: "KOR", name: "South Korea", flag: "🇰🇷" },
  { code: "JP", iso3: "JPN", name: "Japan", flag: "🇯🇵" },
  { code: "GB", iso3: "GBR", name: "United Kingdom", flag: "🇬🇧" },
  { code: "DE", iso3: "DEU", name: "Germany", flag: "🇩🇪" },
  { code: "FR", iso3: "FRA", name: "France", flag: "🇫🇷" },
  { code: "CA", iso3: "CAN", name: "Canada", flag: "🇨🇦" },
  { code: "AU", iso3: "AUS", name: "Australia", flag: "🇦🇺" },
  { code: "AT", iso3: "AUT", name: "Austria", flag: "🇦🇹" },
  { code: "BE", iso3: "BEL", name: "Belgium", flag: "🇧🇪" },
  { code: "BR", iso3: "BRA", name: "Brazil", flag: "🇧🇷" },
  { code: "CL", iso3: "CHL", name: "Chile", flag: "🇨🇱" },
  { code: "CN", iso3: "CHN", name: "China", flag: "🇨🇳" },
  { code: "DK", iso3: "DNK", name: "Denmark", flag: "🇩🇰" },
  { code: "FI", iso3: "FIN", name: "Finland", flag: "🇫🇮" },
  { code: "IN", iso3: "IND", name: "India", flag: "🇮🇳" },
  { code: "ID", iso3: "IDN", name: "Indonesia", flag: "🇮🇩" },
  { code: "IT", iso3: "ITA", name: "Italy", flag: "🇮🇹" },
  { code: "MX", iso3: "MEX", name: "Mexico", flag: "🇲🇽" },
  { code: "NL", iso3: "NLD", name: "Netherlands", flag: "🇳🇱" },
  { code: "NZ", iso3: "NZL", name: "New Zealand", flag: "🇳🇿" },
  { code: "NO", iso3: "NOR", name: "Norway", flag: "🇳🇴" },
  { code: "PL", iso3: "POL", name: "Poland", flag: "🇵🇱" },
  { code: "ES", iso3: "ESP", name: "Spain", flag: "🇪🇸" },
  { code: "SE", iso3: "SWE", name: "Sweden", flag: "🇸🇪" },
  { code: "CH", iso3: "CHE", name: "Switzerland", flag: "🇨🇭" },
  { code: "TR", iso3: "TUR", name: "Türkiye", flag: "🇹🇷" },
  { code: "ZA", iso3: "ZAF", name: "South Africa", flag: "🇿🇦" },
] as const;
export function resolveCountry(code: string | null) {
  return countries.find((c) => c.code === code?.toUpperCase()) ?? countries[0];
}
